version: 2

sphinx:
  configuration: doc/source/conf.py

python:
  install:
    - requirements: requirements_doc.txt
    - method: pip
      path: .

build:
  os: ubuntu-20.04
  tools:
    python: "3.11"
