version: '3'

tasks:
  test:
    cmds:
      - task: run
        vars:
          CLI_ARGS: pytest {{.CLI_ARGS}}

  build:
    dir: env/
    cmds:
      - docker compose build

  format:
    - task: run
      vars:
        CLI_ARGS: black .

  lint:
    - task: run
      vars:
        CLI_ARGS: flake8

  run: # Run a command in the development environment
    dir: env/
    cmds:
      - docker compose run --rm dev {{.CLI_ARGS}}

  ci:
    - task: lint
    - task: test


  check_release:
    cmds:
      - task: run
        vars:
          CLI_ARGS: at verify-version --file VERSION --check-tag