allow-unwrap-in-tests = true
allow-dbg-in-tests = true
max-fn-params-bools = 2
too-many-lines-threshold = 90

# https://rust-lang.github.io/rust-clippy/master/index.html#disallowed_methods
disallowed-methods = [
    { path = "std::env::temp_dir", reason = "Use the tempfile crate instead" },
    { path = "std::panic::catch_unwind", reason = "We compile with `panic = 'abort'`" },
    { path = "std::thread::spawn", reason = "Use `std::thread::Builder` and name the thread" },
]
# https://rust-lang.github.io/rust-clippy/master/index.html#disallowed_types
disallowed-types = [
    { path = "std::sync::Condvar", reason = "Use parking_lot instead" },
    { path = "std::sync::Mutex", reason = "Use parking_lot instead" },
    { path = "std::sync::RwLock", reason = "Use parking_lot instead" },
]
