version:
  current: ./VERSION # Path to the file containing the current version
  release: ./RELEASE # Path to the file containing the next release version
  bump-hooks: [] # List of hooks to run when version is bumped, example below
  update-hooks: [] # List of hooks to run when version is updated, example below
  # bump-hooks:
  #   - method: regex_replace
  #     file_path: doc/source/conf.py
  #     pattern: '^(version\s*=\s*")([^"]+)(")'
  #     repl: '\g<1>@version\g<3>'
extensions: []
vcs:
  username: "Artisan Tools" # User name to use for git commits
  email: "artisan@tools.com" # Email to use for git commits
container:
  engine: docker # Container engine to use - [docker|podman]
  auth:
    method: null # Authentication method to use [env|direct]
    user: null # Username when using direct auth
    token: null # Token when using direct auth
    user_var: null # Env-var name for username when using env auth
    token_var: null # Env-var name for token when using env auth
  registry: null # Registry to use for container images
  options: [] # Additional options to pass to container engine
