graph TD
    A[.atversion<br>5.3.1]
    B["$ at branch my-feature minor<br>"]
    C[Create and switch to my-feature branch]
    D[".at-bump file:<br>TARGET: minor<br><br>CHANGELOG:<br>### Added<br>* Add ability to update version files"]
    E[User modifies .at-bump]
    F[User clicks merge]
    G[CI:<br>Update version + changelog<br>delete .at-bump file]
    H[.atversion<br>5.4.0]

    A --> B
    B --> C
    C --> D
    D --> E
    E --> F
    F --> G
    G --> H


