name: Setup Environment
description: Sets up the environment for rust
inputs:
  cache-key:
    description: Additional cache-key to differentiate builds
    required: false
    default: default
runs:
  using: "composite"
  steps:
    - uses: nixbuild/nix-quick-install-action@v30
      with:
        nix_conf: |
          keep-env-derivations = true
          keep-outputs = true
    # Caching of build tools
    - uses: nix-community/cache-nix-action@v6
      with:
        primary-key: nix-${{ runner.os }}-${{ hashFiles('rs/*.nix', 'rs/flake.lock') }}
    # Caching of cargo dependencies
    - uses: Swatinem/rust-cache@v2
      with:
        workspaces: "rs"
        key: ${{ inputs.cache-key }}
