name: Setup Environment
description: Sets up the environment for rust
runs:
  using: "composite"
  steps:
    - name: Checkout
    - uses: actions/checkout@v4
    - uses: nixbuild/nix-quick-install-action@v30
      with:
        nix_conf: |
          keep-env-derivations = true
          keep-outputs = true
    # Caching of build tools
    - uses: nix-community/cache-nix-action@v6
      with:
        primary-key: nix-${{ runner.os }}-${{ hashFiles('rs/*.nix', 'rs/flake.lock') }}
    # Caching of cargo dependencies
    - uses: Swatinem/rust-cache@v2
      with:
        workspaces: "rs"
