version: '3.8'

services:
    dev:
        build:
            context: ../
            dockerfile: env/Dockerfile
            args:
              USER_ID: ${USER_ID}
        volumes:
            - ../:/app
            - ${SSH_AUTH_SOCK}:/ssh-agent
        environment:
            - SSH_AUTH_SOCK=/ssh-agent
