version: '3.8'

services:
    dev:
        build:
            context: ../
            dockerfile: env/Dockerfile
        environment:
            - SSH_AUTH_SOCK=/ssh-agent
        volumes:
            - ../:/app
            - ${SSH_AUTH_SOCK}:/ssh-agent