name: Release

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run tests
      run: |
        ./ci_bootstrap.sh
        task ci
        task check_release
        task release
