name: Check release requirements

on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Bootstrap
      run: |
        ./ci_bootstrap.sh

    - name: Check version
      run: |
        just check-release

    - name: Run tests locally to verify docker functionality
      run: |
        just local-test