name: Release

on:
  push:
    branches: [master]

jobs:
  tag-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run tests
      run: |
        ./ci_bootstrap.sh
        just ci
        just check-release
        just release
