name: Unit Testing

on: [push]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true
      - uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('rs/*.nix', 'rs/flake.lock') }}
      
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "rs"
      - name: Run tests
        run: nix develop --command cargo test --verbose
        working-directory: rs

  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: Swatinem/rust-cache@v2
      - run: nix develop --command cargo hack check --rust-version --workspace --all-targets --ignore-private
        working-directory: rs