name: Unit Testing

on: [push]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: Swatinem/rust-cache@v2

      - uses: actions/cache@v4
        with:
          path: /nix/store
          key: ${{ runner.os }}-${{ hashFiles('rs/flake.lock') }}
      - name: Check
        run: nix develop --command which cargo
        working-directory: rs
      - name: Run tests
        run: nix develop --command cargo test --verbose
        working-directory: rs

  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: Swatinem/rust-cache@v2
      - run: nix develop --command cargo hack check --rust-version --workspace --all-targets --ignore-private
        working-directory: rs