name: CI

on: [push]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-env
      - name: Run tests
        run: nix develop --command just rs ci
        working-directory: rs

  msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-env
        with:
          cache-key: msrv
      - run: nix develop --command just rs check-msrv
        working-directory: rs